org: kokorolx
app: catch-forwared-mailgun
service: catch-forwared-mailgun

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  environment:
    MAILGUN_API_KEY: ${param:MAILGUN_API_KEY}

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
